config/routes.rb
WebPortal::Application.routes.draw do

  resources :tokens

  resources :purges

  resources :accounts do
    resources :account_permissions
  end

  resources :hostnames do 
    get 'success'
  end

  resources :rulesets do
    post 'clone'
    post 'reorder'
    resources :rules
  end

  devise_for :users, :controllers => { :registrations => "registrations" , :passwords => "passwords", :confirmations => "confirmations"}

  namespace :admin do 
    
    resources :users do 
      get 'confirm'
      get 'disable'
      get 'enable'
    end

    resources :rulesets do 
    end

  end

  match '/reports' => 'reports#index'
  
  root :to => "accounts#index"

end

app/models/token.rb
class Token
  include Mongoid::Document
  include Mongoid::Timestamps

  field :secret, type: String
  field :location, type: String
  field :name, type: String

  index :name => 1

  belongs_to :account, :index => true 

  before_create :create_secret_key

  validates_inclusion_of :location, :in => %w( header cookie url), :message => "Valid token options are headers, cookie or URL"

  attr_protected :secret

private
   def create_secret_key
   	self.secret = SecureRandom.base64(32)
   end
   
end

app/controllers/tokens_controller.rb
class TokensController < ApplicationController
 
  before_filter :authenticate_user!
  before_filter :load_account

  def index
    @tokens = @account.tokens.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tokens }
    end
  end


  # GET /tokens/new
  # GET /tokens/new.json
  def new
    @token = @account.tokens.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @token }
    end
  end


  # POST /tokens
  # POST /tokens.json
  def create
    @token = @account.tokens.new(params[:token])

    respond_to do |format|
      if @token.save
        format.html { redirect_to tokens_path, notice: 'Token was successfully created.' }
        format.json { render json: @token, status: :created, location: @token }
      else
        format.html { render action: "new" }
        format.json { render json: @token.errors, status: :unprocessable_entity }
      end
    end
  end

  
  # DELETE /tokens/1
  # DELETE /tokens/1.json
  def destroy
    @token = @account.tokens.find(params[:id]).revoke
    @token.destroy

    respond_to do |format|
      format.html { redirect_to tokens_url }
      format.json { head :no_content }
    end
  end

private

  def load_account
    @account = current_account
  end

end

app/helpers/tokens_helper.rb
module TokensHelper
end

app/views/tokens/_first_time.html.erb
<h3>Secure Tokens are a mechanism where you can secure your content with a token.  The token gets validated on the ScaleSimple edge network so there is no concern about incurring additional origin load to ensure the request is valid.  Tokens work as follows:</h3>

<ul>
<li>First, a user visits your website in order for a token to be generated.  This can be any page on your site, usually a login form is where this type of logic happens, but it can be anywhere.  On your origin server you will compute a few things:</li>
	<ul>
	<li>The location of the required security values.  To validate a token, we require at minimum an expiration and the token.  You can choose to require these values either in the cookie, the header or the url itself.  The header is useful for API based requests, while the cookie is better suited for browser based requests.  We support URL for use cases like emailing secure links to downloads, but in general the URL method is not advised.</li>

	<li>The expiration value of the token.  Typically this is set to expire in a relatively short period of time for security reasons, but it can be any time in the future.  The value of this field is in Unix epoch format and can be set either in a header (X-SS-Expiration) or a cookie (ss_expiration)</li>

	<li>The token itself.  This is the actual token that we will compute and validate on our edge network.  This can be stored in the header (X-SS-Token) or in a cookie (ss_token).  The token is computed using the following algorithm  MD5(key,MD5(key,expiration,url)) where key is a shared secret key only known between us and your origin server.  Your key is automatically generated by us once you create a token.</li>
	</ul>
</ul>

<p/><h5>Some things to be aware of when using tokens: </h5>

<ul>
	<li> The token is removed from either the cookie, the header or the URL request before passing the request to origin and before caching the object.  The reason is both for security (not transmitting tokens) and for ensuring that the same URL with multiple tokens will cache identically</li>
	<li>When we compute the token, we use the URL exactly as it appears in the request.  Please ensure you are aware of any query strings and know the exact URL that will be used when generating a token.</li>
</ul>

app/views/tokens/_form.html.erb
<div class="row">

<div class="span6">

<%= form_for(@token) do |f| %>
  <% if @token.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@token.errors.count, "error") %> in token form:</h2>

      <ul>
      <% @token.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

   <div class="control-group">
    <label class="control-label" for="token_secret">Token Location <a href='#' id='token-tooltip'> <i class='icon-question-sign'></i></a></label>
    <div class="controls">
       <select name='token[location]' id='token_location' >
        <option selected value="">Choose Token Location</option>
        <option value="cookie">Cookie</option>
        <option value="header">Header</option>
        <option value="url">URL</option> 
      </select>
    </div>
  </div>

    <div class="control-group">
    <label class="control-label" for="token_name">Token Name </label>
    <div class="controls">
      <%= f.text_field :name %> 
    </div>
  </div>

 

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                tokens_path, :class => 'btn' %>
  </div>
<% end %>
</div>


<div class="span6">
   <div id='token_url_html' style='display:none;'>
    <h4>When using the URL option, you must supply 2 query parameters with your request</h4>
      <ul><li>ss_token which contains the generated token value</li><li>ss_expiration which contains the epoch expiration time</li></ul>
      <p>For details on how to generate these values, please click <a href='#'>Here</a>
  </div>
  <div id='token_header_html' style='display:none;'>
     <h4>When using the Header option, you must set 2 headers with your request</h4>
     <ul><li>X-SS-Token which contains the generated token value</li><li>X-SS-Expiration which contains the epoch expiration time</li></ul>
  </div>
  <div id='token_cookie_html' style='display:none;'>
      <h4>When using the Cookie option, you must set 2 cookies with your request</h4>
      <ul><li>ss_token which contains the generated token value</li><li>ss_expiration which contains the epoch expiration time</li></ul>
  </div>
</div>

</div>

app/views/tokens/_table.html.erb
 <table class="table table-bordered table-striped table-highlight">
      <thead>
        <tr>

          <th> Account </th>
          <th> Name </th>
          <th> Token </th>
          <th> Location </th>
          <th> Created</th>
          <th><%=t '.actions', :default => t("helpers.actions") %></th>
        </tr>
      </thead>
      <tbody>
        <% tokens.each do |token| %>
          <tr>
            <td><%= token.account.name %></td>
            <td><%= token.name %> </td>
            <td><%= token.secret %></td>
            <td><%= token.location %> </td>
            <td><%= token.created_at.to_s(:summary) %></td>
            <td>             
               <%= link_to content_tag('i', '', class: 'icon-remove'), token, confirm: "Are you sure you want to revoke this token?", method: :delete, "modal-warning" => "tokens" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

app/views/tokens/edit.html.erb
<h1>Editing token</h1>

<%= render 'form' %>

<%= link_to 'Show', @token %> |
<%= link_to 'Back', tokens_path %>

app/views/tokens/index.html.erb
<% if @tokens.size == 0 %> 
  <%= render 'first_time' %> 
  <%= link_to 'Generate you first token', new_token_path %>

<% else %> 

<div class='widget stacked'>


  <div class="widget-header">
     <i class="icon-lock"></i>
    <h3><%=t '.title', :default => "Tokens" %></h3>
    <%= link_to t('.new_token', :default => t("New Token")),
              new_token_path,
              :class => 'btn btn-secondary' %>
  </div>

  <div class="widget-content">
    <%= render 'tokens/table', :tokens => @tokens  %> 
  </div> <!-- widget content -->
</div> <!-- widget --> 

<% end %> 

app/views/tokens/new.html.erb
<h1>Generate a new secure token</h1>

<br/>
<%= render 'form' %>

app/views/tokens/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_token_path(@token) %> |
<%= link_to 'Back', tokens_path %>