config/routes.rb
WebPortal::Application.routes.draw do

  resources :tokens

  resources :purges

  resources :accounts do
    resources :account_permissions
  end

  resources :hostnames do 
    get 'success'
  end

  resources :rulesets do
    post 'clone'
    post 'reorder'
    resources :rules
  end

  devise_for :users, :controllers => { :registrations => "registrations" , :passwords => "passwords", :confirmations => "confirmations"}

  namespace :admin do 
    
    resources :users do 
      get 'confirm'
      get 'disable'
      get 'enable'
    end

    resources :rulesets do 
    end

  end

  match '/reports' => 'reports#index'
  
  root :to => "accounts#index"

end

app/models/hostname.rb
require 'dns_util'

class Hostname
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name, type: String
  field :origin, type: String
  field :version, type: Integer
  field :cname, type: String
  field :valid_origin_ips, type: Array    #Each IP maps to a backend in VCL, it must match when we resolve the origin name

  embeds_one :hostname_status

  belongs_to :account, :index=>true
  belongs_to :ruleset, :index=>true, :inverse_of => :ruleset
  belongs_to :active_ruleset, :class_name => "Ruleset", :index => true, :foreign_key => "active_ruleset_id", :inverse_of => :ruleset
  #belongs_to :pending_ruleset, :class_name => "Ruleset", :index => true, :foreign_key => "ruleset_id", :inverse_of => :ruleset

  index :name=>1
  index "hostname_status.host"=>1

  attr_protected :cname  #CNAME MUST BE GENERATED BY US !!! 

  # TODO - REMOVE PENDING
  scope :ready_for_vcl, where(:name.ne=>nil).in("hostname_status.host"=> ["ACTIVE","READY","PENDING"])
  #scope :active, where("hostname_status.host" => "ACTIVE")

  before_validation(:on=>:create) do 
    validate_package
    set_hostname
    set_origin
    set_cname
    set_valid_origin_ips
    set_status
    validate_ruleset_status
  end

  before_validation(:on=>:update) do
   # unless self.hostname_status
      set_status
      validate_origin
      set_valid_origin_ips
      validate_ruleset_status
   # end
  end

  before_destroy :prepare_for_destroy
  after_save :activate_ruleset
  after_create :create_dns_entry
  
  validates :name, :presence=>true, :uniqueness=>true, :format => { :with => /[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?$/, :message => "Invalid hostname format"}
  validates :origin, :presence=>true
  validates :cname, :presence=>true
  validates :ruleset_id, :presence=>true

  

  def has_tokens?
    false #self.account.security_tokens.count > 0
  end

  def valid_for_vcl?
    !self.active_ruleset.nil? && !self.lb_vip.nil?
  end

  def new_config_valid_for_vcl?
    !self.lb_vip.nil?
  end

  def status
    self.hostname_status.host
  end

  def active?
    self.hostname_status.host=="ACTIVE"
  end

  def cname_active?
    self.hostname_status.cname=="ACTIVE"
  end

  def origin_active?
    self.hostname_status.origin == "ACTIVE"
  end

  def has_active_ruleset?
    !self.active_ruleset.nil?
  end

  def resolved?
    self.hostname_status.cname == "RESOLVED"
  end

  def activate
    self.hostname_status.update_attribute(:host,$HOSTNAME_STATUS[:active])
    DnsMailer.hostname_active(self.account.user.email,self).deliver
    return true
  end

  def active
    self.where("hostname_status.host" =>'ACTIVE')
  end

  def pending
    self.where("hostname_status.host" =>'PENDING')
  end

  def set_active_ruleset(ruleset)
    Rails.logger.info("Deactivating Previous Ruleset" + self.ruleset.id.to_s)
    self.active_ruleset.deactivate if self.has_active_ruleset?
    self.update_attribute(:active_ruleset_id, self.ruleset_id)
  end

  def reset_pending_ruleset
    return unless self.active_ruleset
    self.update_attribute(:ruleset_id, self.active_ruleset_id)
  end

 private

  # TODO
  def create_dns_entry
    msg = { :action => "create_hostname", :payload => { :hostname => self.name, :id => self.id } }.to_json
    MqLib.publish(msg,'jobs.hostname')
    DnsMailer.hostname_created(self.account.user.email,self).deliver
  end

  #-----------------------------------------------
  # We need to lookup the hostname and its CNAMEs
  # to make sure it does not resolve to AWS ELB
  # 
  # Right now we can not create "dynamic" backends
  # which is what ELB is , so... we have a problem
  #-----------------------------------------------
  

  def invalid_origin?
    if DnsUtil.origin_aws_elb?(self.origin)
      self.errors.add(:base,"Sorry, Amazon AWS Elastic Load Balancers are currently not supported as origin servers")
      return true
    end

    # no letters means an ip address so lets validate it
    if self.origin.match(/[a-zA-Z]/).nil? && !IPAddress.valid?(self.origin)
      self.errors.add(:base, "Sorry you used an invalid IP Address format for your origin")
      return true
    end

    false
  end

  def set_origin
    self.origin = self.origin.blank? ? "origin." + self.name : self.origin.gsub(/http\:\/\/|https\:\/\//,"")
    return false if invalid_origin?
  end

  def set_hostname
    if self.name
      self.name = self.name.gsub(/http\:\/\/|https\:\/\//,"") 
      self.name = self.name.gsub(/\/.*$/,'')
      self.name = self.name.downcase
    end
    return true
  end

  def set_cname
    self.cname = self.name+"."+$CNAME_SUFFIX
  end
  
  def set_status
    self.build_hostname_status
  end

  #---------------------------------------------------------
  # In varnish we want to use DNS backends.  Each valid_origin_ip
  # will ultimately become a valid backend for this hostname.
  # To do this we need to pre-create a backend
  # for every valid IP that a customer origin can resolve to.  
  # Since some customers use
  # GSLB or failover we may not know all the ips upfront. 
  # This allows us to ensure if they failover DNS we can 
  # address the situation and not try a down host.
  #---------------------------------------------------------
  def set_valid_origin_ips
    ips = Array.new

    if !self.valid_origin_ips.nil?
      self.valid_origin_ips.each { |ip|
        if !ip.match(/^(\d+\.){3}\d+$/)
          self.errors.add(:base,"Invalid IP address format specificed in Additional Valid IPs")
          return false
        end
        ips << ip
      }
    end

    if (extra_ips = DnsUtil.lookup_arecs(self.origin)) != false 
     ips = ips + extra_ips
     self.valid_origin_ips = ips.uniq
    else
      self.errors.add(:base,"Sorry unable to validate additional ips")
      false
    end
  end

  def validate_origin
    invalid_origin?
  end

  def validate_ruleset_status
    return false unless self.ruleset
    errors.add(:base,"Sorry you can not assign a ruleset with an invalid status") and return false if self.ruleset.is_invalid?
    true
  end


  # TODO
  def validate_package
    # return true
    # #unless self.account.hostnames.count >= self.account.max_hostnames
    # #  return true
    # #end
    if self.account.hostnames.count >= self.account.max_hostnames
    self.errors.add(:base, "You have exceeded the number of authorized hostnames for this account.  Either remove one of your hostnames or ask your site administrator to upgrade the packages for this account.")
    return false
    end
    true
  end

  def prepare_for_destroy
    return true #unless self.hostname_status
    if ["ACTIVE","READY"].include? self.status
      self.hostname_status.host="PENDING_REMOVAL"
      self.errors.add(:base, "Hostname was in a 'READY' or 'ACTIVE' state.  Deactivation has been scheduled.")
      return false
    end
    return true
  end

  def activate_ruleset
    return unless self.new_record? || self.ruleset_id_changed? || self.hostname_status.host_changed?
    Rails.logger.info("Activating ruleset with id " + self.ruleset.id.to_s)
    self.ruleset.publish_ruleset(self.id)
  end


end

app/controllers/hostnames_controller.rb
class HostnamesController < ApplicationController
  before_filter :authenticate_user!
  before_filter :load_account
  # GET /hostnames
  # GET /hostnames.json
  def index
    @filter = params[:filter] || 'all'
    @hostnames =  @account.hostnames.where("hostname_status.host" => { "$in" => filter(@filter)} ).desc(:created_at)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @hostnames }
    end
  end

  # GET /hostnames/1
  # GET /hostnames/1.json
  def show
    @hostname = @account.hostnames.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @hostname }
    end
  end

  # GET /hostnames/new
  # GET /hostnames/new.json
  def new
    @hostname = @account.hostnames.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @hostname }
    end
  end

  # GET /hostnames/1/edit
  def edit
    @hostname = @account.hostnames.find(params[:id])
  end

  # POST /hostnames
  # POST /hostnames.json
  def create
    @hostname = @account.hostnames.new(params[:hostname])
    respond_to do |format|
      if @hostname.save
        format.html { redirect_to hostname_success_url(@hostname.id), notice: 'Hostname was successfully created.' }
        format.json { render json: @hostname, status: :created, location: @hostname }
      else
        format.html { render action: "new", :notice=>@hostname.errors.full_messages.join(", ") }
        format.json { render json: @hostname.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /hostnames/1
  # PUT /hostnames/1.json
  def update
    @hostname = @account.hostnames.find(params[:id])

    respond_to do |format|
      if @hostname.update_attributes(params[:hostname])
        format.html { redirect_to hostnames_url, notice: 'Hostname was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit", :notice=>@hostname.errors.full_messages.join(", ")  }
        format.json { render json: @hostname.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hostnames/1
  # DELETE /hostnames/1.json
  def destroy
    @hostname = @account.hostnames.find(params[:id])
    @hostname.destroy

    respond_to do |format|
      unless @hostname.errors.blank?
        flash[:notice]=@hostname.errors.full_messages.join(",")
      end
      format.html { redirect_to hostnames_url }
      format.json { head :no_content }
    end
  end

  def success
    @hostname = @account.hostnames.find(params[:hostname_id])
  end

private

  def filter(f)
    f.downcase == 'all' ? ['ACTIVE', 'PENDING'] : [ f.upcase ]
  end

  def load_account
    redirect_to new_account_path, :notice => "You need to create an account before you create any hostnames" and return if !current_account
    @account = current_account
  end

  def host_statuses(filter)

  end

end

app/helpers/hostnames_helper.rb
module HostnamesHelper

	def hostname_status_icon(status)
		case status
		when 'ACTIVE'
			"<span class=\"label label-success\">Active</span>"
		when 'PENDING'
			"<span class=\"label label-warning\">Pending</span>"
		else
			"<span class=\"label label-important\">Error</span>"
		end
	end

	def hostname_filters(filter)
		all = filter == 'all' ? 'All' : link_to('All', hostnames_path(:filter => 'all'))
		pending = filter == 'pending' ? 'Pending' : link_to('Pending', hostnames_path(:filter => 'pending'))
		active = filter == 'active' ? 'Active' : link_to('Active', hostnames_path(:filter => 'active'))

        all + ' | ' + pending + ' | ' + active
	end

end

app/views/hostnames/_form.html.erb
<%= form_for @hostname, :html => { :class => 'form-horizontal' } do |f| %>

<% if @hostname.errors.any? %>
    <div class="error-box">
      <div class="alert alert-error">
      <% @hostname.errors.full_messages.each do |msg| %>
        <p><%= msg %>
      <% end %>
      </div>
    </div>
<% end %>

<div id="rootwizard">
          <div class='widget'>
          <div class='widget-content'>
          <ul>
            <li><a href="#tab1" data-toggle="tab"><span class="label">1</span>Create Hostname</a></li>
            <li><a href="#tab2" data-toggle="tab"><span class="label">2</span>Choose Ruleset</a></li>
            <li><a href="#tab3" data-toggle="tab"><span class="label">3</span>Set Origin</a></li>
          </ul>
   

          <div class="tab-content">

              <div class="tab-pane" id="tab1">
                  <br/>
                    <h3>First, pick a hostname that you want to cache, this is the hostname users type in their browser</h3>
                    <div class="controls input-prepend">
                      <% if @hostname.new_record? %>
                       <span class="add-on">http://</span><span style="font-size:18px;"><%= f.text_field :name, :class => 'text_field' %></span>
                      <% else %>
                         <span class="add-on">http://<%= @hostname.name %></span>
                      <% end %> 
                    </div>
              </div>

              <div class="tab-pane" id="tab2">
              
                  <br/>
                    <h3>Now, choose a ruleset you want to associate with this hostname.  Dont worry if you're not sure, you can always change it later by editing this hostname.  In fact, whenever you want to assign a ruleset, just edit your hostname and change the ruleset assigned to it.</h3>
                    <div class="controls">
                      <% if @hostname.new_record? %>
                        <%= f.select :ruleset_id, @account.valid_rulesets.asc(:name).map{|r| [r.name,r.id]}, {:class => 'text_field' } %>
                      <% else %> 
                        <%= f.select :ruleset_id, @account.valid_rulesets.asc(:name).map{|r| [r.name,r.id]}, {:class => 'text_field' }, { :onChange => '$("#ruleset_chg_warning").modal();'} %>
                      <% end %> 
                      No rulesets?  <%= link_to "Create one now and come back", new_ruleset_path %> 
                   </div>
              </div>

              <div class="tab-pane" id="tab3">
                  <br/>
                    <h3>Okay.  Now, we need to know how to contact your server to forward requests.  Enter either the IP Address (recommended) or hostname of the server we should use to forward requests.  This must be different than the hostname in Step 1.</h3>
                    <div class="controls">
                     IP or Hostname of Origin: <%= f.text_field :origin, :class => 'text_field' %>
                    </div>

                     <br/>Optional: For advanced users, some customers have multiple IP Addresses that are valid for them. This can be due to DNS round robin, GSLB, or other reasons.  If you need to whitelist additional valid IPs for your origin, please do so here.
                     <a id='add-new-ip' class="btn btn-medium" href="#"><i class="icon-plus"></i>Add New IP</a>
                     <div class="controls" id="ip-controls">
                      <% i = 0 %>
                      <% !@hostname.valid_origin_ips.nil? && @hostname.valid_origin_ips.each do |ip| %>
                       <div id="valid_ips_<%= i.to_s %>">
                         <input class="text_field" id="valid_ip_<%= i.to_s %>" name="hostname[valid_origin_ips][]" value="<%= ip %>" size="30" type="text" >&nbsp;&nbsp;<a href='#'><i class="icon-remove" onClick='$("#valid_ips_<%= i.to_s %>").remove();return false;'></i></a><br/><br/>
                       </div>
                      <% i += 1 %>
                      <% end %>
                     </div>
                     <br/>
                     <div style='text-align:center;'>
                        <%= f.submit nil, :class => 'btn btn-primary' %>
                     </div>
              </div>
          
            <ul class="pager wizard">
              <li class="previous first" style="display:none;"><a href="#">First</a></li>
              <li class="previous"><a href="#">Previous</a></li>
              <li class="next last" style="display:none;"><a href="#">Last</a></li>
                <li class="next"><a href="#">Next</a></li>
            </ul>
          </div>  <!-- end tab content --> 

        </div> <!-- end widget content --> 

      </div> <!-- end widget --> 

</div> <!-- end rootwizard --> 
  
<% end %>

 <div class="modal fade " id="ruleset_chg_warning">
                 <div class="modal-header">
                   <a class="close" data-dismiss="modal">×</a>
                   <h3>WARNING !</h3>
                 </div>
                 <div class="modal-body">
                   <p>Changing a ruleset for a hostname will automatically publish this new configuration for that hostname once you save.  If this is NOT what you want then close this window and click Cancel.  If you DO want to change the ruleset for your hostname and understand that it will be automatically activated then go for it !</p>
                 </div>
                 <div class="modal-footer">
                   <a data-dismiss="modal" class="btn">Got it !</a>
                 </div>
  </div>

<script type='text/javascript'>

  $(document).ready(function() {
    var randomNum = Math.ceil(Math.random()*2); 
    var field_id = 'valid_ips_' + randomNum;

    $('#add-new-ip').click(function() {
      $('#ip-controls').prepend("<div id=\"" + field_id + "\">IP Address: <input class=\"text_field\" id=\"" + field_id + "\" name=\"hostname[valid_origin_ips][]\" size=\"30\" type=\"text\" ><a href='#'>&nbsp;&nbsp;<i class=\"icon-remove\" onClick='$(\"#" + field_id + "\").remove();return false;'></i></a><br/><br/></div>");
      return false;
    });

    function removeIp(ip) {
      $('input[name=ip]').remove();
    }

    $('#rootwizard').bootstrapWizard({'tabClass': 'bwizard-steps'});  
    window.prettyPrint && prettyPrint()

  });
</script>

app/views/hostnames/edit.html.erb
<%- model_class = Hostname -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/hostnames/index.html.erb
  <%- model_class = Hostname -%>
<div class='widget '>

  

  <div class="widget-header">
    <i class="icon-cloud"></i>
    <h3><%=t '.title', :default => "Hostnames" %></h3>
    <span  style="float:middle;"><%= link_to t('.new_hostname', :default => t("New Hostname")),
              new_hostname_path,
              :class => 'btn btn-secondary' %></span>
  </div>

  <div class="widget-content"> 

  <div>Filter by: <%= hostname_filters(@filter).html_safe %> </div>
  <p/>

  <table class="table table-bordered table-striped table-highlight">
    <thead>
      <tr>
        <th><%= model_class.human_attribute_name(:name) %></th>
        <th> Active Ruleset</th>
        <th> Pending Ruleset </th>
        <th><%= model_class.human_attribute_name(:origin) %></th>
        <th>Created</th>
        <th>Status</th>
        <th><%=t '.actions', :default => t("helpers.actions") %></th>
      </tr>
    </thead>
    <tbody>
      <% @hostnames.each do |hostname| %>
        <tr>
          <td><%= link_to hostname.name, hostname_path(hostname) %></td>
          <td><%= link_to hostname.active_ruleset.name, ruleset_path(hostname.active_ruleset) if hostname.active_ruleset %></td>
          <td>
            <% if hostname.active_ruleset_id == hostname.ruleset_id %> 
            None
            <% else %> 
            <%= link_to hostname.ruleset.name, ruleset_path(hostname.ruleset) %>
            <% end %> 
          </td>
          <td><%= hostname.origin %></td>
          <td ><%=hostname.created_at.strftime("%m/%d/%Y %H:%M") %></td>
          <td> <%= hostname_status_icon(hostname.hostname_status.host).html_safe %>
          <td nowrap>
            <%= link_to content_tag('i', '', class: 'icon-pencil'),
                        edit_hostname_path(hostname)%> 
              &nbsp;&nbsp;&nbsp;&nbsp;
             <%= link_to content_tag('i', '', class: 'icon-trash'), hostname, confirm: "Are you sure you want to delete #{hostname.name}?", method: :delete, "modal-warning" => "hostnames" %>

          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  </div> <!-- widget-content --> 
</div> <!-- widget --> 

app/views/hostnames/new.html.erb
<%- model_class = Hostname -%>
<div>
  <h2><%=t '.title', :default => [:'new_hostname', 'Create new Hostname'], :model => model_class.model_name.human %></h2>
</div>
<%= render :partial => 'form' %>

app/views/hostnames/show.html.erb
<div class='widget stacked'>
    <div class='widget-header'><h3><%= @hostname.name %></h3> </div>

    <div class='widget-content'>

     <h4>Ruleset</h3> 
      <%= link_to @hostname.ruleset.name , ruleset_rules_path(@hostname.ruleset) %> 
      
     <p/><p/><br/>

     <h4>Origin</h4>
     <%= @hostname.origin %> 

     <p/><p/><br/>
 
     <h4>Valid Origin IP Addresses </h4>
     <% @hostname.valid_origin_ips.each do |h| %> 
         <%= (h + '<br/>').html_safe %> 
      <% end %>  

    </div>

</div>

app/views/hostnames/success.html.erb
<div class="alert alert-success">
<h4>Congratulations !!   It may take a few minutes for your hostname to be available.  In the meantime, please ensure the following steps are completed</h4>
</div>

<br/><br/>

<div class="lead" > CNAME your new cache domain <strong><em><%= @hostname.name %></strong></em> to <strong><em><%= @hostname.cname %></strong></em></div><br/>
<div class="lead">Check the status of your hostname by visiting <%= link_to 'your hostnames overview page' , hostnames_url %> </div>