config/routes.rb
WebPortal::Application.routes.draw do

  resources :tokens

  resources :purges

  resources :accounts do
    resources :account_permissions
  end

  resources :hostnames do 
    get 'success'
  end

  resources :rulesets do
    post 'clone'
    post 'reorder'
    resources :rules
  end

  devise_for :users, :controllers => { :registrations => "registrations" , :passwords => "passwords", :confirmations => "confirmations"}

  namespace :admin do 
    
    resources :users do 
      get 'confirm'
      get 'disable'
      get 'enable'
    end

    resources :rulesets do 
    end

  end

  match '/reports' => 'reports#index'
  
  root :to => "accounts#index"

end

app/views/layouts/_head.html.erb
<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "ScaleSimple" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <link href="http://fonts.googleapis.com/css?family=Open+Sans:400italic,600italic,400,600" rel="stylesheet">
    <%= stylesheet_link_tag "application", :media => "all" %>

  

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">

      <div class="navbar-inner">
  
        <div class="container">

          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>

          <a class="brand" href="#"><img src='/assets/ss_logo2.png' width='300px' height='80px'></a>

          <% if current_user %>
          <div class="collapse nav-collapse">

            <ul class="nav">
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Accounts
                  <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <% current_user.authorized_accounts.only(:id, :name).each do |a| %>
                  <li>
                  <%= link_to a.name, a  %>
                  </li>
                  <% end %>
                </ul>
              </li>
              
            </ul>
            
            <% if current_account %> 
            <ul class="nav"><li style="color: #FFFFFF;padding: 10px 15px;font-size: 11px;">Current Account: <%= current_account.name %> </li></ul>
            <% end %>

            <ul class="nav pull-right">
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <%= current_user.email %>
                  <b class="caret"></b>
                </a>
                <ul class="dropdown-menu"> 
                  <li>
                  <%= link_to "Sign Out", "/users/sign_out", :method=>:delete  %>
                  </li>  
                  <li>
                    <%= link_to "Change Password", edit_user_registration_path %>
                  </li>    
                </ul>
              </li>
            </ul>
          </div><!--/.nav-collapse -->
          <% end %>

        </div>
      </div>
    </div>


<% if current_user %> 
<div class="subnavbar">

  <div class="subnavbar-inner">
  
    <div class="container">
      
      <a class="btn-subnavbar collapsed" data-toggle="collapse" data-target=".subnav-collapse">
        <i class="icon-reorder"></i>
      </a>

      <div class="subnav-collapse collapse">
        <ul class="mainnav">
        
          <li <%= active_menu('hostnames',params[:controller]).html_safe %> >
            <a href="/hostnames">
              <i class="icon-cloud"></i>
              <span>Hostnames</span>
            </a>              
          </li>
          
          <li <%= active_menu('rulesets',params[:controller]).html_safe %> >
            <a href="/rulesets">
              <i class="icon-magic"></i>
              <span>Rulesets</span>
            </a>              
          </li>

          <li <%= active_menu('purges',params[:controller]).html_safe %> >
            <a href="/purges">
              <i class="icon-remove-sign"></i>
              <span>Purge Content</span>
            </a>              
          </li>

          <li <%= active_menu('reports',params[:controller]).html_safe %> >
            <a href="/reports">
              <i class="icon-bar-chart"></i>
              <span>Reports</span>
            </a>              
          </li>

          <li <%= active_menu('tokens',params[:controller]).html_safe %> >
            <a href="/tokens">
              <i class="icon-lock"></i>
              <span>Tokens</span>
            </a>              
          </li>
        
        </ul>
      </div> <!-- /.subnav-collapse -->

    </div> <!-- /container -->
  
  </div> <!-- /subnavbar-inner -->

</div> <!-- /subnavbar -->
<% end %> 

app/views/layouts/_sidebar.html.erb
<div class="well sidebar-nav">
    <% if current_account %>
    <ul class="nav nav-list">
        <li class="nav-header"><%= current_account ? current_account.name : "none" %></li>
        <li><%= link_to "Hostnames", hostnames_url  %></li>
        <li><%= link_to "Rulesets", rulesets_url  %></li>
        <li><%= link_to "Purge", purges_url %></li>
    </ul>
    <% else %>
        <ul class="nav nav-list">
        <li class="nav-header"><%= link_to "<Create Account>", new_account_path %></li>
    </ul>
    <% end %>
</div><!--/.well -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <%= render "layouts/head" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
  </head>
  <body>
    <%= render "layouts/navbar"  %>

 <div class="main">

    <div class="container">

      <div class="row">
        
        <div class="span12">
          
          <% if flash[:notice] %>
            <div class="alert alert-block"> 
              <button type="button" class="close" data-dismiss="alert">&times;</button>
              <%= flash[:notice] %>
            </div>
          <% end %>
          <% if flash[:error] %>
            <div class="alert alert-error">
              <button type="button" class="close" data-dismiss="alert">&times;</button>
              <%= flash[:error] %>
            </div>
          <% end %>
          <% if flash[:alert]  %>
            <div class="alert alert-error">
              <button type="button" class="close" data-dismiss="alert">&times;</button>
              <%= flash[:alert] %>
            </div>
          <% end %>

            <%= yield %>

        </div>

      </div><!--/row-->

      <footer>
        <p>&copy; ScaleSimple 2013</p>
      </footer>

    </div> <!-- /container -->

  </div> <!-- main --> 

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    

  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <%= render "layouts/head" %>
    <%= javascript_include_tag "application" %>
  </head>
  <body>
    <%= render "layouts/navbar"  %>

   <div class="main">

    <div class="container">

      <div class="row">
        
        <div class="span12">
          <% if flash[:notice] %>
            <div class="alert alert-block"> 
              <button type="button" class="close" data-dismiss="alert">&times;</button>
              <%= flash[:notice] %>
            </div>
          <% end %>
          <% if flash[:error]  %>
            <div class="alert alert-error">
              <button type="button" class="close" data-dismiss="alert">&times;</button>
              <%= flash[:error] %>
            </div>
          <% end %>
          <% if flash[:alert]  %>
            <div class="alert alert-error">
              <button type="button" class="close" data-dismiss="alert">&times;</button>
              <%= flash[:alert] %>
            </div>
          <% end %>

            <%= yield %>

        </div>

      </div><!--/row-->

      <footer>
        <p>&copy; ScaleSimple 2013</p>
      </footer>

    </div> <!-- /container -->

  </div> <!-- main --> 

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>