config/routes.rb
WebPortal::Application.routes.draw do

  resources :tokens

  resources :purges

  resources :accounts do
    resources :account_permissions
  end

  resources :hostnames do 
    get 'success'
  end

  resources :rulesets do
    post 'clone'
    post 'reorder'
    resources :rules
  end

  devise_for :users, :controllers => { :registrations => "registrations" , :passwords => "passwords", :confirmations => "confirmations"}

  namespace :admin do 
    
    resources :users do 
      get 'confirm'
      get 'disable'
      get 'enable'
    end

    resources :rulesets do 
    end

  end

  match '/reports' => 'reports#index'
  
  root :to => "accounts#index"

end

app/models/account.rb
class Account
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name, type: String
  field :company_name, type: String
  field :address, type: String
  field :city, type: String
  field :state, type: String
  field :postal_code, type: String
  field :primary_contact, type: String
  field :primary_contact_email, type: String
  field :primary_phone, type: String
  field :secondary_phone, type: String
  field :max_hostnames, type: Integer, :default=>3

  index :name=>1
  index "account_permissions.user_id"=>1
  index "account_permissions.title"=>1
  
  belongs_to :user, :index=>true
  has_many :hostnames
  has_many :purges
  has_many :rulesets, :dependent=>:destroy
  has_many :tokens

  embeds_many :account_permissions

  validates :user_id, :presence=>true
  validates :name, :presence=>true
  validates :primary_contact, :presence=>true
  validates :primary_contact_email, :presence=>true
  validates :primary_phone, :presence=>true

  before_create :make_admin
  #after_create :make_default_rulesets

  def unassigned_rulesets
    self.rulesets.where(:status => $RULESET_STATUS[:unassigned])
  end

  def valid_rulesets
    self.rulesets.where(:status.ne => $RULESET_STATUS[:invalid])
  end

  def make_admin
    self.account_permissions << AccountPermission.new(:user=>self.user, :title=>"Admin")
  end

  def make_default_rulesets
    Ruleset.make_default_rulesets(self)
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

  before_filter :authenticate_user!
  before_filter :allow_one_account, :only => [:new, :create]

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = current_user.authorized_accounts.asc(:name)
    redirect_to new_account_path and return if @accounts.size == 0 

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @accounts }
    end
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
    @account = self.current_account = current_user.authorized_accounts.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @account }
    end
  end

  # GET /accounts/new
  # GET /accounts/new.json
  def new
    @account = Account.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @account }
    end
  end

  # GET /accounts/1/edit
  def edit
    @account = Account.find(params[:id])
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(params[:account])
    @account.user = current_user

    respond_to do |format|
      if @account.save
        format.html { redirect_to hostnames_path, notice: 'Account was successfully created.' }
        format.json { render json: @account, status: :created, location: @account }
      else
        format.html { render action: "new" }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /accounts/1
  # PUT /accounts/1.json
  def update
    @account = Account.find(params[:id])

    respond_to do |format|
      if @account.update_attributes(params[:account])
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account = Account.find(params[:id])
    @account.destroy

    respond_to do |format|
      format.html { redirect_to accounts_url }
      format.json { head :no_content }
    end
  end

  private

  def allow_one_account
    redirect_to '/404.html' and return unless current_user.authorized_accounts.size == 0 || is_global_admin?
  end


end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.erb
<%= form_for @account, :html => { :class => 'form-horizontal' } do |f| %>
 
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :required=>true, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :company_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :company_name, :class => 'text_field' %>
    </div>
  </div>
  
  <div class="control-group">
    <%= f.label :primary_contact, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :primary_contact, :required=>true, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :primary_contact_email, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :primary_contact_email, :required=>true, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :primary_phone, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :primary_phone, :required=>true, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :secondary_phone, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :secondary_phone, :class => 'text_field' %>
    </div>
  </div>
<div class="control-group">
    <%= f.label :address, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :address, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :city, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :city, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :state, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :state, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :postal_code, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :postal_code, :class => 'text_field' %>
    </div>
  </div>
  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                accounts_path, :class => 'btn' %>
  </div>
<% end %>

app/views/accounts/_permissions.html.erb
<% account_permission = AccountPermission.new(:title=>"Admin") %>
<%= form_for([account, account_permission]) do |f| %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>User</th>
      <th>Permission</th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% account.account_permissions.each do |permission| %>
      <tr>
        <td><%= permission.user.email %></td>
        <td><%= permission.title %></td>
        <td>
          <% if (permission.removable_by?(current_user)) %>
         
          <%= link_to content_tag('i', '', class: 'icon-trash'), account_account_permission_path(account,permission), confirm: "Remove user from account", method: :delete, "modal-warning" => "acct_perms" %>
          <% end %>
        </td>
      </tr>
    <% end %>
      <tr>
        <td><%= f.text_field :email, :required=>true %></td>
        <td>Admin<%= f.hidden_field :title %></td>
        <td><%= f.submit %></td>
      </tr>
    </form>
  </tbody>
</table>
<% end %>

app/views/accounts/_show.html.erb
<dl class="dl-horizontal">
  
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @account.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:company_name) %>:</strong></dt>
  <dd><%= @account.company_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:address) %>:</strong></dt>
  <dd><%= @account.address %></dd>
  <dt><strong><%= model_class.human_attribute_name(:city) %>:</strong></dt>
  <dd><%= @account.city %></dd>
  <dt><strong><%= model_class.human_attribute_name(:state) %>:</strong></dt>
  <dd><%= @account.state %></dd>
  <dt><strong><%= model_class.human_attribute_name(:postal_code) %>:</strong></dt>
  <dd><%= @account.postal_code %></dd>
  <dt><strong><%= model_class.human_attribute_name(:primary_contact) %>:</strong></dt>
  <dd><%= @account.primary_contact %></dd>
  <dt><strong><%= model_class.human_attribute_name(:primary_contact_email) %>:</strong></dt>
  <dd><%= @account.primary_contact_email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:primary_phone) %>:</strong></dt>
  <dd><%= @account.primary_phone %></dd>
  <dt><strong><%= model_class.human_attribute_name(:secondary_phone) %>:</strong></dt>
  <dd><%= @account.secondary_phone %></dd>
  <dt><strong>Created By:</strong></dt>
  <dd><%= @account.user.email %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('Back to Account List'),
              accounts_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_account_path(@account), :class => 'btn' %>
  <% if is_global_admin? %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              account_path(@account),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
  <% end %> 
</div>

app/views/accounts/edit.html.erb
<%- model_class = Account -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/accounts/index.html.erb
<%- model_class = Account -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:primary_contact_email) %></th>
      <th><%= model_class.human_attribute_name(:primary_phone) %></th>
      <th>Created By</th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= link_to account.name, account_path(account) %></td>
        <td><%= account.primary_contact_email %></td>
        <td><%= account.primary_phone %></td>
        <td><%= account.user.email %></td>
        <td><%=l account.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_account_path(account), :class => 'btn btn-mini' %>
          <% if is_global_admin? %> 
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      account_path(account),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
          <% end %> 
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/accounts/new.html.erb
<%- model_class = Account -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.accounts.new', 'Create New Account'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/accounts/show.html.erb
<%- model_class = Account -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>
<div class="tabbable"> <!-- Only required for left/right tabs -->
  <ul class="nav nav-tabs">
    <li class="active"><a href="#tab_show" data-toggle="tab">Details</a></li>
    <li><a href="#tab_permissions" data-toggle="tab">Permissions</a></li>
  </ul>
  <div class="tab-content">
    <div class="tab-pane active" id="tab_show">
      <%= render "show", :account=>@account, :model_class=>Account %>
    </div>
    <div class="tab-pane" id="tab_permissions">
      <%= render "permissions", :account=>@account, :model_class=>Account %>
    </div>
  </div>
</div>

<script>
$(document).ready(function(){
  // Javascript to enable link to tab
var hash = document.location.hash;
var prefix = "t_";
if (hash) {
    $('.nav-tabs a[href='+hash.replace(prefix,"")+']').tab('show');
} 

// Change hash for page-reload
$('.nav-tabs a').on('shown', function (e) {
    window.location.hash = e.target.hash.replace("#", "#" + prefix);
});
});
</script>